node_defaults:
  keyfile: ~/.ssh/id_rsa
  username: runner

nodes:
- name: "node-all-in-one"
  address: "127.0.0.1"
  internal_address: "127.0.0.1"
  roles: ["control-pla0e", "worker"]

cluster_name: "test-local-k8s.com"

services:
    packages:
        install:
        - conntrack
        - kmod
        - ethtool
        - ebtables
        - socat
        - curl
        - openssl
        - unzip
        - policycoreutils-python-utils

plugins:
  kubernetes-dashboard:
    install: true
  nginx-ingress-controller:
    install: true
  calico:
    install: true

rbac:
  accounts:
  - name: superadmin
    role: cluster-admin
  admission: pss
  pss:
    pod-security: enabled
