name: Manage Patches
on:
  release:
    types: [released]
jobs:
  delete_patches_on_release:
    runs-on: ubuntu-latest
    # Release can be done only in main branch or dedicated vN.N.N_branch support branches
    if: github.event.release.target_commitish == 'main' || endsWith(github.event.release.target_commitish, '_branch')
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NCCLPLCI_PAT }}
          # By default, tag is checked out. It needs to check out branch to commit to.
          ref: ${{ github.event.release.target_commitish }}
      - run: |
         find kubemarine/patches/ -not -path "kubemarine/patches/__init__.py" -not -path "kubemarine/patches/" -delete
         cp kubemarine/resources/etalons/patches/* kubemarine/patches/
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Delete all patches after release
