name: Prettier

on:
  workflow_dispatch:

jobs:
  Prettier_Check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # Check out the repository first.
      - uses: actionsx/prettier@v2
        with:
          # prettier CLI arguments.
          args: --check .
