name: Prettier

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prettier_plugins: "@prettier/plugin-xml,@prettier-plugin-sh,@prettier-plugin-properties,@prettier-plugin-jinja-template"
