name: Publish Artifacts
on:
  release:
    types: [created]
<<<<<<< HEAD
=======
  push:
    branches:
      - 'main'
env:
  TAG_NAME: ${{ github.event.release.tag_name || (github.ref == 'refs/heads/main' && 'main') }}
>>>>>>> d7fe4ef43b40838d41fd9e0bf287162c2110881d
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
<<<<<<< HEAD
      - run: docker build . -t ghcr.io/netcracker-technology/kubetool:${{ github.event.release.tag_name }}
      - run: echo ${{secrets.GITHUB_TOKEN}} | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - run: docker push ghcr.io/netcracker-technology/kubetool:${{ github.event.release.tag_name }}
=======
      - run: docker build . -t ghcr.io/netcracker-technology/kubetool:${{ env.TAG_NAME }}
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - run: docker push ghcr.io/netcracker-technology/kubetool:${{ env.TAG_NAME }}
>>>>>>> d7fe4ef43b40838d41fd9e0bf287162c2110881d
