name: Publish Artifacts
on:
  release:
    types: [created]
  push:
    branches:
      - 'main'
env:
  TAG_NAME: ${{ github.event.release.tag_name || (github.ref == 'refs/heads/main' && 'main') }}
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t ghcr.io/netcracker-technology/kubetool:${{ env.TAG_NAME }}
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - run: docker push ghcr.io/netcracker-technology/kubetool:${{ env.TAG_NAME }}
