name: Unit Tests
on:
  push:
    branches:
      - '**'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t kubetools --build-arg BUILD_TYPE=test --no-cache .
      - run: docker run --entrypoint=python3 kubetools -m unittest discover -s /opt/kubetools/test/unit -t /opt/kubetools/test/unit
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t kubetools --build-arg BUILD_TYPE=test --no-cache .
      - run: docker run --entrypoint=/bin/bash kubetools -c "python3 /usr/local/bin/coverage run -m unittest discover -s /opt/kubetools/test/unit -t /opt/kubetools/test/unit; python3 /usr/local/bin/coverage report -m" > /tmp/report.txt
      - run: cat /tmp/report.txt; PERCENTAGE=$(cat /tmp/report.txt | tail -1 | awk '{print $4}' | tr -dc '0-9')
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t kubetools --build-arg BUILD_TYPE=test --no-cache .
      - run: docker run --entrypoint=/bin/bash kubetools -c "/usr/local/bin/pylint kubetool test --disable fixme || exit 0"
